-- 选课系统触发器脚本：维护课程已选人数等（Kingbase/PostgreSQL兼容）
-- 在执行前请先运行表结构脚本。

-- 清理旧触发器/函数
DROP TRIGGER IF EXISTS TRG_SC_INC_COURSE_NUM ON TB_STUDENT_COURSE;
DROP TRIGGER IF EXISTS TRG_SC_DEC_COURSE_NUM ON TB_STUDENT_COURSE;
DROP TRIGGER IF EXISTS TRG_SC_DEL_COURSE_NUM ON TB_STUDENT_COURSE;
DROP TRIGGER IF EXISTS TRG_SC_GRADE_CHECK ON TB_STUDENT_COURSE;
DROP FUNCTION IF EXISTS FN_SC_INC_COURSE_NUM();
DROP FUNCTION IF EXISTS FN_SC_DEC_COURSE_NUM();
DROP FUNCTION IF EXISTS FN_SC_DEL_COURSE_NUM();
DROP FUNCTION IF EXISTS FN_SC_GRADE_CHECK();

-- 触发函数：插入选课后增加课程已选人数
CREATE OR REPLACE FUNCTION FN_SC_INC_COURSE_NUM()
RETURNS TRIGGER AS $$
DECLARE
    v_capacity INT;
    v_selected INT;
BEGIN
    IF NEW.STATUS = '1' THEN
        UPDATE TB_COURSE
        SET SELECTED_NUM = SELECTED_NUM + 1
        WHERE COURSE_ID = NEW.COURSE_ID
        RETURNING CAPACITY, SELECTED_NUM INTO v_capacity, v_selected;

        IF v_selected > v_capacity THEN
            RAISE EXCEPTION '课程容量已满';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 触发器：AFTER INSERT
CREATE TRIGGER TRG_SC_INC_COURSE_NUM
AFTER INSERT ON TB_STUDENT_COURSE
FOR EACH ROW
EXECUTE FUNCTION FN_SC_INC_COURSE_NUM();

-- 触发函数：状态由选课改为退课时减少课程已选人数
CREATE OR REPLACE FUNCTION FN_SC_DEC_COURSE_NUM()
RETURNS TRIGGER AS $$
DECLARE
    v_capacity INT;
    v_selected INT;
BEGIN
    IF OLD.STATUS = '1' AND NEW.STATUS = '0' THEN
        UPDATE TB_COURSE
        SET SELECTED_NUM = GREATEST(SELECTED_NUM - 1, 0)
        WHERE COURSE_ID = NEW.COURSE_ID;
    ELSIF OLD.STATUS = '0' AND NEW.STATUS = '1' THEN
        -- 允许从退课恢复到选课，保持人数一致
        UPDATE TB_COURSE
        SET SELECTED_NUM = SELECTED_NUM + 1
        WHERE COURSE_ID = NEW.COURSE_ID
        RETURNING CAPACITY, SELECTED_NUM INTO v_capacity, v_selected;

        IF v_selected > v_capacity THEN
            RAISE EXCEPTION '课程容量已满';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 触发器：AFTER UPDATE
CREATE TRIGGER TRG_SC_DEC_COURSE_NUM
AFTER UPDATE ON TB_STUDENT_COURSE
FOR EACH ROW
EXECUTE FUNCTION FN_SC_DEC_COURSE_NUM();

-- 触发函数：删除选课记录时回收人数
CREATE OR REPLACE FUNCTION FN_SC_DEL_COURSE_NUM()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.STATUS = '1' THEN
        UPDATE TB_COURSE
        SET SELECTED_NUM = GREATEST(SELECTED_NUM - 1, 0)
        WHERE COURSE_ID = OLD.COURSE_ID;
    END IF;
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

-- 触发器：BEFORE DELETE
CREATE TRIGGER TRG_SC_DEL_COURSE_NUM
BEFORE DELETE ON TB_STUDENT_COURSE
FOR EACH ROW
EXECUTE FUNCTION FN_SC_DEL_COURSE_NUM();

-- 可选触发函数：成绩范围校验（0-100），若已有 CHECK 约束可视为冗余保护
CREATE OR REPLACE FUNCTION FN_SC_GRADE_CHECK()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.GRADE IS NOT NULL AND (NEW.GRADE < 0 OR NEW.GRADE > 100) THEN
        RAISE EXCEPTION '成绩必须在0到100之间';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 可选触发器：INSERT/UPDATE 时校验成绩
CREATE TRIGGER TRG_SC_GRADE_CHECK
BEFORE INSERT OR UPDATE ON TB_STUDENT_COURSE
FOR EACH ROW
EXECUTE FUNCTION FN_SC_GRADE_CHECK();
